Issue 100
OpenLiberty/space-rover-mission pull request #107
Opened 2022-08-22 19:08 UTC by uhryniuk

Includes all kubernetes files and build scripts to for all the images used. 

Was able to get kubernetes work with local images as well.

2023-03-03 15:47 UTC, jacobwdv commented
@kabicin should we be merging this or do your changes work outside of these?

2023-03-03 17:14 UTC, kabicin commented
Yes we can merge these changes bundled as part of v3 once I get another review on my additional commits.

2023-03-17 20:34 UTC, pgunapal requested changes
@kabicin I see you changed the ports for all the services in the Docker-compose files, would this break the current V3 game? Can players still clone the repo and play the game as-is (w/ containers) with the V3 devices? I think we should make the back-ward compatibility easier, since there are replicas in the different geos, that may still want to use the old container offline behaviour.

2023-03-21 18:16 UTC, kabicin commented
@pgunapal good point, the networking is a bit different in docker vs kubernetes. I adjusted the port for leaderboard to work correctly with docker-compose scripts and added mpConfig environment variables so a rebuild won't be required.

2023-03-22 18:31 UTC, pgunapal approved these changes
LGTM

2026-05-06 13:42 UTC, closed without merging